// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Decode$Json from "@zooshme/rescript-json/src/Decode.res.mjs";

var decode = Decode$Json.map3(Decode$Json.field("statusCode", Decode$Json.$$int), Decode$Json.field("message", Decode$Json.string), Decode$Json.field("name", Decode$Json.string), (function (statusCode) {
        return function (message) {
          return function (name) {
            return {
                    statusCode: statusCode,
                    message: message,
                    name: name
                  };
          };
        };
      }));

var $$Error = {
  decode: decode
};

var decode$1 = Decode$Json.map(Decode$Json.field("id", Decode$Json.string), (function (id) {
        return {
                id: id
              };
      }));

var Data = {
  decode: decode$1
};

var decode$2 = Decode$Json.map2(Decode$Json.field("data", Decode$Json.nullable(decode$1)), Decode$Json.field("error", Decode$Json.nullable(decode)), (function (data, error) {
        if (data !== undefined) {
          return {
                  TAG: "Data",
                  _0: data
                };
        } else if (error !== undefined) {
          return {
                  TAG: "Error",
                  _0: error
                };
        } else {
          return "Empty";
        }
      }));

var $$Response = {
  decode: decode$2
};

var Emails = {};

export {
  $$Error ,
  Data ,
  $$Response ,
  Emails ,
}
/* decode Not a pure module */
